[env:esp32-dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = default_ffat.csv
monitor_speed = 115200
monitor_filters = time

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0

build_flags =
    -D SERIAL_DEBUG
    ; -D DEVICE_MDCW_V2       ; Uncomment for V2 (with proximity)

; Override file (gitignored) untuk credentials lokal:
; Buat platformio_local.ini dengan isi:
; [env:esp32-dev]
; build_flags =
;     -D WIFI_SSID='"ssid_anda"'
;     -D WIFI_PASS='"password"'
;     -D MQTT_BROKER='"10.201.40.1"'
;     -D MQTT_USER='"apps"'
;     -D MQTT_PASS='"apps"'
;     -D MQTT_PORT=1883
