name: Deploy IoT Server to Server

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file from Secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Stop & remove old app containers (tidak menyentuh postgres & emqx)
        run: |
          docker stop forwarder ota-app forming-app || true
          docker rm forwarder ota-app forming-app || true

      - name: Build images from source
        run: |
          docker compose -f docker-compose.prod.yml build --no-cache backend ota forming

      - name: Start all services
        run: |
          docker compose -f docker-compose.prod.yml up -d --no-recreate

      - name: Prune unused Docker images
        run: |
          docker image prune -f
